[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Crypticcoin"
authors = [{name = "CrypticCoin Admin", email = "admin@crypticcoin.io"}]
dynamic = ["version", "description"]
